// <auto-generated />
namespace EfTest.AdventureWorks.Data.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FullText_ProductName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullText_ProductName));
        
        string IMigrationMetadata.Id
        {
            get { return "201601202209233_FullText_ProductName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
