// <auto-generated />
namespace EfTest.AdventureWorks.Data.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FullText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullText));
        
        string IMigrationMetadata.Id
        {
            get { return "201601202055424_FullText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
