// <auto-generated />
namespace EfTest.AdventureWorks.Data.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewTestEntity1Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTestEntity1Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201601252250451_NewTestEntity1Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
